name: minimeli

services:
  database:
    image: mysql:8.1

    environment:
      MYSQL_DATABASE: minimeli
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

    volumes:
      - database_data:/var/lib/mysql

    ports:
      - "3306:3306"

  idp:
    image: quay.io/keycloak/keycloak

    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://database:3306/keycloak
      KC_DB_USERNAME: root

      KC_BOOTSTRAP_ADMIN_USERNAME: root
      KC_BOOTSTRAP_ADMIN_PASSWORD: password

    command: start-dev --hostname=idp

    ports:
      - "8080:8080"


volumes:
  database_data: