name: minimeli

services:
  database:
    image: postgres:18

    environment:
      POSTGRES_DB: minimeli
      POSTGRES_HOST_AUTH_METHOD: trust

    volumes:
      - database_data:/var/lib/postgresql

    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  idp:
    image: quay.io/keycloak/keycloak

    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/keycloak
      KC_DB_USERNAME: postgres

      KC_BOOTSTRAP_ADMIN_USERNAME: root
      KC_BOOTSTRAP_ADMIN_PASSWORD: password

    command: start-dev --hostname=idp

    ports:
      - "8080:8080"

    depends_on:
      database:
        condition: service_healthy



volumes:
  database_data: